#ifndef DCGLOBAL_H
#define DCGLOBAL_H

#define DC_START_SESSION_TAG_STR "S:"
#define DC_END_SESSION_TAG_STR "E:"
#define DC_DEFAULT_SESSION_TIMEOUT 3000
#define DC_DEFAULT_KEEPALIVE_TIMEOUT 100
#define DC_CHANNEL_COUNT 126
#define DC_DEFAULT_OFFLINE_TIMEOUT 1000
#define DC_MAX_SIZE_OF_RF_PACKET 32


#endif // !DCGLOBAL_H

