#ifndef _MESH_APP_MEMORY_CONFIG_H
#define _MESH_APP_MEMORY_CONFIG_H
/*****************************************************************************
 *
 *  BT Mesh application memory configuration
 *
 *  Autogenerated file, do not edit
 *
 ****************************************************************************/


#define MESH_CFG_MAX_ELEMENTS                   1
#define MESH_CFG_MAX_MODELS                     4
#define MESH_CFG_MAX_APP_BINDS                  4
#define MESH_CFG_MAX_SUBSCRIPTIONS              4
#define MESH_CFG_MAX_NETKEYS                    4
#define MESH_CFG_MAX_APPKEYS                    4
#define MESH_CFG_MAX_DEVKEYS                    1
#define MESH_CFG_NET_CACHE_SIZE                 16
#define MESH_CFG_RPL_SIZE                       32
#define MESH_CFG_MAX_SEND_SEGS                  4
#define MESH_CFG_MAX_RECV_SEGS                  4
#define MESH_CFG_MAX_VAS                        4
#define MESH_CFG_MAX_PROV_SESSIONS              2
#define MESH_CFG_MAX_PROV_BEARERS               2
#define MESH_CFG_MAX_GATT_CONNECTIONS           3
#define MESH_CFG_GATT_TXQ_SIZE                  4
#define MESH_CFG_MAX_PROVISIONED_DEVICES        0
#define MESH_CFG_MAX_PROVISIONED_DEVICE_NETKEYS 0
#define MESH_CFG_MAX_FOUNDATION_CLIENT_CMDS     0
#define MESH_CFG_MAX_FRIENDSHIPS                1
#define MESH_CFG_FRIEND_MAX_SUBS_LIST           5
#define MESH_CFG_FRIEND_MAX_TOTAL_CACHE         5
#define MESH_CFG_FRIEND_MAX_SINGLE_CACHE        5

#endif